### ISSUE TITLE
Case study in the wild

### ISSUE THREAD

**Issue by gmmoura** [vttale/serve-stale#8]
Dear authors,

This is not an issue, but I though it was easy to report it this way.

We've done a research study on caching and TTL relationship during DDoS attacks, and we show the presence the serve stale in the wild. 

This may somehow support your draft -- it shows that once things go really bad, stale content is in practice your only hope.

full text: https://www.isi.edu/%7ejohnh/PAPERS/Moura18b.pdf

/giovane

**Comment by vttale** [comment]
Thanks a ton for the feedback.  May we include a reference to the paper?

**Comment by puneetsood** [comment]
Are you asking about the resolver centricity experiment? This is it:
https://blog.nzrs.net.nz/resolvers-centricity-detection/

**Comment by vttale** [comment]
For Giovane's benefit, since it might seem odd why Puneet asked about the other URL... we'd been talking just this morning about parent/child NS rrsets and how different resolvers handle them.

My question was about Giovane's, et al, paper which he linked in the first comment and is supportive of Serve Stale as a resiliency mechanism.  The paper is apparently not yet presented to ACM IMC but is public, and just wanted to make sure it was cool if we used it in the imminently updated draft.

**Comment by gmmoura** [comment]
just so you know, the paper has not been presented yet, but it is accepted  and will be presented in two weeks. You can check it out at: https://conferences.sigcomm.org/imc/2018/program/

Feel free to refer to this URL I posted, that's a stable one that one of our co-authors hosts.  The copyrights belong to the authors.

giovane

**Comment by wkumari** [comment]
Done in fed6863
